function out_tmd = make_trans_mtx_desc()

out_tmd.states = cell(1,0);
out_tmd.trans = struct('init',cell(1,0),'final',cell(1,0),'rate',cell(1,0),'driven',cell(1,0),'visible',cell(1,0));

out_tmd.states{end+1} = 'Ground';
out_tmd.states{end+1} = 'Excited';

% rates here are defaults/initial guesses
out_tmd.trans(end+1) = struct(  'init','Ground',...
                                'final','Excited',...
                                'rate',1,...
                                'driven',1,...
                                'visible',0);

out_tmd.trans(end+1) = struct(  'init','Excited',...
                                'final','Ground',...
                                'rate',3,...
                                'driven',0,...
                                'visible',1);

% also a guess
out_tmd.scale = 1;                            
                            
end